In [21]:
import torch

# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

import sys
print(sys.getsizeof(int))

device = torch.device("cpu")

print('Using device:', device)
print()


import sys
print(sys.getsizeof(int))


mat = torch.eye(10,dtype=bool)
print(mat)


x = torch.Tensor([1,2,3,4])

print(x.flip([0]))


ran = torch.randn(3, 3)
print(ran)
ran = ran.transpose(0,1)

print(ran)

a_full = torch.randn(102400, 102400, dtype=torch.float)
a_full.cuda()
b_full = torch.randn(102400, 102400, dtype=torch.float)
b_full.cuda()
ab_full = a_full @ b_full

Using device: cuda

416
Using device: cpu

416
tensor([[ True, False, False, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False, False],
        [False, False, False, False,  True, False, False, False, False, False],
        [False, False, False, False, False,  True, False, False, False, False],
        [False, False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False, False, False,  True]])
tensor([4., 3., 2., 1.])
tensor([[-1.0588, -0.4035, -1.0850],
        [-0.0031, -0.0404,  0.2441],
        [-0.7567, -0.8755,  0.7851]])
tensor([[-1.058

RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:73] data. DefaultCPUAllocator: not enough memory: you tried to allocate 41943040000 bytes. Buy new RAM!