In [ ]:
import torch

# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

import sys
print(sys.getsizeof(int))

device = torch.device("cpu")

print('Using device:', device)
print()


import sys
print(sys.getsizeof(int))


mat = torch.eye(10,dtype=bool)
print(mat)


x = torch.Tensor([1,2,3,4])

print(x.flip([0]))


ran = torch.randn(3, 3)
print(ran)
ran = ran.transpose(0,1)

print(ran)

a_full = torch.randn(102400, 102400, dtype=torch.float)
a_full.cuda()
b_full = torch.randn(102400, 102400, dtype=torch.float)
b_full.cuda()
ab_full = a_full @ b_full

Using device: cuda

416
Using device: cpu

416
tensor([[ True, False, False, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False, False],
        [False, False, False, False,  True, False, False, False, False, False],
        [False, False, False, False, False,  True, False, False, False, False],
        [False, False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False, False, False,  True]])
tensor([4., 3., 2., 1.])
tensor([[ 2.3604, -2.6431,  0.5367],
        [-0.7409,  0.0693,  0.2405],
        [-2.0363, -1.0388,  0.9153]])
tensor([[ 2.360

In [ ]:
from src.benchmarking.vanilla.benchmark_vanilla import check_and_benchmark
import sys

# RANDOM BIG MAT

import numpy as np


size = 100
sec_size = 5

mat = np.random.randint(2, size=(size, size)).tolist()

print(f"{mat[0][1]} {sys.getsizeof(mat[0][1])}")
print(sys.getsizeof(mat))

sum = 0
for i in range(0, size):
    for j in range(0, size):
        sum += sys.getsizeof(mat[i][j])

print(sum)

opt_mat, circuit, _, process_time, initial_rss, final_rss = check_and_benchmark(mat, sec_size)

print(sum)


print(f"process time: {process_time} seconds")
print(f"initial memory: {initial_rss / 1048576} mb")
print(f"final memory: {final_rss / 1048576} mb")

import os
import psutil
from src.algorithm.vanilla.cnot_synthesis import cnot_synthesis

pid = os.getpid()
ps = psutil.Process(pid)

print(ps.num_threads())